-   id: cci-validate
    name: 'circleci config validate'
    entry: cci-validate.sh
    files: '\.circleci/config\.yaml$'
    language: 'script'
    description: "Runs `circleci config validate`, requires circleci cli"
